server_port: 8081
check_period: 10h
parse_period: 10h
sites_for_parsing:
  - https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc
  - https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt
  - https://api.openproxylist.xyz/http.txt
  - https://api.proxyscrape.com/v2/?request=getproxies&protocol=http
  - https://api.proxyscrape.com/v2/?request=getproxies&protocol=https 
  - https://openproxy.space/list/http
  - https://proxyspace.pro/http.txt
  - https://proxyspace.pro/https.txt
  - https://raw.githubusercontent.com/AGDDoS/AGProxy/master/proxies/http.txt
  - https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/http.txt
  - https://raw.githubusercontent.com/andigwandi/free-proxy/main/proxy_list.txt
  - https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/http_proxies.txt
  - https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/https_proxies.txt
  - https://raw.githubusercontent.com/aslisk/proxyhttps/main/https.txt
  - https://raw.githubusercontent.com/elliottophellia/yakumo/master/results/http/global/http_checked.txt
  - https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt
  - https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/https.txt
  - https://raw.githubusercontent.com/hendrikbgr/Free-Proxy-Repo/master/proxy_list.txt
  - https://raw.githubusercontent.com/im-razvan/proxy_list/main/http.txt
  - https://raw.githubusercontent.com/KUTlime/ProxyList/main/ProxyList.txt
  - https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt
  - https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt
  - https://raw.githubusercontent.com/MrMarble/proxy-list/main/all.txt
  - https://raw.githubusercontent.com/noarche/proxylist-socks5-sock4-exported-updates/main/http-online.txt
  - https://raw.githubusercontent.com/ObcbO/getproxy/master/file/http.txt
  - https://raw.githubusercontent.com/ObcbO/getproxy/master/file/https.txt 
  - https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/http/http.txt
  - https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/https/https.txt
  - https://raw.githubusercontent.com/r00tee/Proxy-List/main/Https.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt
  - https://raw.githubusercontent.com/Sage520/Proxy-List/main/http.txt
  - https://raw.githubusercontent.com/saisuiu/Lionkings-Http-Proxys-Proxies/main/free.txt
  - https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/http_proxies.txt
  - https://raw.githubusercontent.com/themiralay/Proxy-List-World/master/data.txt
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt
  - https://raw.githubusercontent.com/Tsprnay/Proxy-lists/master/proxies/http.txt
  - https://raw.githubusercontent.com/Tsprnay/Proxy-lists/master/proxies/https.txt
  - https://raw.githubusercontent.com/tuanminpay/live-proxy/master/http.txt
  - https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/http.txt
  - https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/https.txt
  - https://raw.githubusercontent.com/Vann-Dev/proxy-list/main/proxies/http.txt
  - https://raw.githubusercontent.com/Vann-Dev/proxy-list/main/proxies/https.txt
  - https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt
  - https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt
  - https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt
  - https://raw.githubusercontent.com/zloi-user/hideip.me/main/http.txt
  - https://raw.githubusercontent.com/zloi-user/hideip.me/main/https.txt
  - https://www.proxy-list.download/api/v1/get?type=http